"""
MLS Draft Survival Analysis (2020-2025)
Cross-references draft picks with 2026 active MLS roster data to compute:
- Survival rate by draft year
- Survival rate by draft round
- Survival rate by nationality (US vs international)
- Survival rate by college conference
"""

import csv
import os
import json
from collections import defaultdict

DATA_DIR = os.path.join(os.path.dirname(__file__), "..", "data")
OUT_DIR = os.path.join(DATA_DIR, "processed")

# ── Draft picks 2020-2025 from Wikipedia ────────────────────────────────────
# Format: (year, overall_pick, round, team_drafted, player_name, pos, nationality, college)

DRAFT_PICKS = [
    # ── 2025 (90 picks, 3 rounds) ──
    (2025,1,"R1","San Diego FC","Manu Duah","MF","Ghana","UC Santa Barbara"),
    (2025,2,"R1","San Jose Earthquakes","Max Floriani","DF","USA","Saint Louis"),
    (2025,3,"R1","Chicago Fire FC","Dean Boltz","FW","USA","Wisconsin"),
    (2025,4,"R1","Colorado Rapids","Alex Harris","FW","USA","Cornell"),
    (2025,5,"R1","San Jose Earthquakes","Reid Roberts","DF","USA","San Francisco"),
    (2025,6,"R1","Colorado Rapids","Matthew Senanou","DF","USA","Xavier"),
    (2025,7,"R1","St. Louis City SC","Emil Jääskeläinen","FW","Finland","Akron"),
    (2025,8,"R1","Sporting Kansas City","Jansen Miller","DF","USA","Indiana"),
    (2025,9,"R1","Charlotte FC","Mikah Thomas","DF","USA","UConn"),
    (2025,10,"R1","D.C. United","Hakim Karamoko","FW","USA","NC State"),
    (2025,11,"R1","FC Dallas","Enzo Newman","DF","USA","Oregon State"),
    (2025,12,"R1","Colorado Rapids","Efetobo Aror","MF","USA","Portland"),
    (2025,13,"R1","CF Montréal","Michael Adedokun","MF","Nigeria","Ohio State"),
    (2025,14,"R1","Portland Timbers","Ian Smith","DF","USA","Denver"),
    (2025,15,"R1","Vancouver Whitecaps FC","Tate Johnson","DF","USA","North Carolina"),
    (2025,16,"R1","Colorado Rapids","Sydney Wathuta","FW","Canada","Vermont"),
    (2025,17,"R1","New York City FC","Max Murray","DF","USA","Vermont"),
    (2025,18,"R1","New England Revolution","Donovan Parisian","GK","USA","San Diego"),
    (2025,19,"R1","Real Salt Lake","Jesús Barea","FW","Spain","Missouri State"),
    (2025,20,"R1","LA Galaxy","Jason Bucknor","DF","USA","Michigan"),
    (2025,21,"R1","Real Salt Lake","Max Kerkvliet","GK","USA","UConn"),
    (2025,22,"R1","Los Angeles FC","Alec Hughes","FW","USA","UMass"),
    (2025,23,"R1","Toronto FC","Reid Fisher","DF","USA","San Diego State"),
    (2025,24,"R1","San Diego FC","Ian Pilcher","DF","USA","Charlotte"),
    (2025,25,"R1","Minnesota United FC","Roman Torres","MF","USA","Creighton"),
    (2025,26,"R1","Colorado Rapids","Josh Copeland","MF","USA","Detroit Mercy"),
    (2025,27,"R1","Orlando City SC","Joran Gerbet","MF","France","Clemson"),
    (2025,28,"R1","Seattle Sounders FC","Ryan Baer","MF","USA","West Virginia"),
    (2025,29,"R1","Real Salt Lake","Lineker Rodrigues dos Santos","FW","Brazil","Marshall"),
    (2025,30,"R1","Real Salt Lake","Sergi Solans","FW","Spain","Oregon State"),
    (2025,31,"R2","San Diego FC","Harrison Bertos","DF","USA","Washington"),
    (2025,32,"R2","San Jose Earthquakes","Nick Fernandez","MF","USA","Portland"),
    (2025,33,"R2","Chicago Fire FC","Travis Smith Jr.","DF","USA","Wake Forest"),
    (2025,34,"R2","Sporting Kansas City","Anthony Samways","DF","USA","Ohio State"),
    (2025,35,"R2","New England Revolution","Eric Howard","DF","USA","Georgetown"),
    (2025,36,"R2","Nashville SC","Alioune Ka","FW","USA","Cornell"),
    (2025,37,"R2","St. Louis City SC","Joey Zalinsky","DF","USA","Rutgers"),
    (2025,38,"R2","Colorado Rapids","Charlie Harper","DF","Australia","North Carolina"),
    (2025,39,"R2","Toronto FC","Michael Sullivan","MF","USA","Pittsburgh"),
    (2025,40,"R2","D.C. United","Daniel Ittycheria","FW","USA","Princeton"),
    (2025,41,"R2","FC Dallas","Sam Sarver","FW","USA","Indiana"),
    (2025,42,"R2","Austin FC","Riley Thomas","DF","USA","North Carolina"),
    (2025,43,"R2","Minnesota United FC","Kieran Chandler","DF","USA","UConn"),
    (2025,44,"R2","CF Montréal","Arik Duncan","FW","USA","California"),
    (2025,45,"R2","Vancouver Whitecaps FC","Nikola Djordjevic","DF","USA","SMU"),
    (2025,46,"R2","Orlando City SC","Titus Sandy Jr","DF","USA","Clemson"),
    (2025,47,"R2","Charlotte FC","Andrew Johnson","DF","USA","Cornell"),
    (2025,48,"R2","Houston Dynamo FC","Bo Cummins","DF","USA","Wake Forest"),
    (2025,49,"R2","Real Salt Lake","Nick Dang","DF","USA","Virginia"),
    (2025,50,"R2","CF Montréal","Caden Grabfelder","FW","USA","Penn State"),
    (2025,51,"R2","Columbus Crew","Cesar Ruvalcaba","DF","USA","SMU"),
    (2025,52,"R2","Inter Miami CF","Bailey Sparks","MF","USA","SMU"),
    (2025,53,"R2","Atlanta United FC","Ronan Wynne","DF","New Zealand","Denver"),
    (2025,54,"R2","New York City FC","Collin McCamy","MF","USA","Northwestern"),
    (2025,55,"R2","Minnesota United FC","Logan Dorsey","FW","USA","Kentucky"),
    (2025,56,"R2","San Diego FC","Samy Kanaan","FW","USA","San Diego"),
    (2025,57,"R2","Orlando City SC","Collins Oduro","FW","Ghana","Indiana"),
    (2025,58,"R2","Seattle Sounders FC","Demian Alvarez","DF","USA","Seattle"),
    (2025,59,"R2","Real Salt Lake","Trace Alphin","GK","USA","Wake Forest"),
    (2025,60,"R2","LA Galaxy","Jacob Woznicki","FW","USA","Hofstra"),
    (2025,61,"R3","San Diego FC","Donovan Sessoms","FW","USA","Sacramento State"),
    (2025,62,"R3","Colorado Rapids","Donavan Phillip","FW","Saint Lucia","NC State"),
    (2025,63,"R3","Chicago Fire FC","Geni Kanyane","DF","South Africa","Dayton"),
    (2025,64,"R3","Sporting Kansas City","Leon Koehl","MF","Germany","Maryland"),
    (2025,65,"R3","New England Revolution","C. J. Williams","DF","USA","Boston College"),
    (2025,66,"R3","Nashville SC","Ethan Ballek","MF","USA","South Carolina"),
    (2025,67,"R3","St. Louis City SC","Colin Welsh","GK","USA","Western Michigan"),
    (2025,68,"R3","Colorado Rapids","Shawn Smart","DF","USA","Clemson"),
    (2025,69,"R3","Toronto FC","Joseph Melto Quiah","FW","Liberia","Dayton"),
    (2025,70,"R3","D.C. United","Jonah Biggar","DF","USA","South Carolina"),
    (2025,71,"R3","FC Dallas","Mohamed Cisset","DF","Mali","Penn State"),
    (2025,72,"R3","Austin FC","Patrick Gryczewski","FW","USA","Rhode Island"),
    (2025,73,"R3","CF Montréal","Arthur Duquenne","DF","France","Clemson"),
    (2025,74,"R3","Portland Timbers","Lukas Burns","GK","USA","Providence"),
    (2025,75,"R3","Colorado Rapids","Matthew Van Horn","MF","USA","Georgetown"),
    (2025,76,"R3","Seattle Sounders FC","Trace Terry","FW","USA","Bowling Green"),
    (2025,77,"R3","Charlotte FC","Barzee Blama","FW","USA","Mercer"),
    (2025,78,"R3","New York City FC","A. J. Smith","FW","Denmark","Virginia"),
    (2025,79,"R3","Real Salt Lake","Liam O'Gara","MF","USA","Wake Forest"),
    (2025,80,"R3","FC Cincinnati","Ben Augee","MF","USA","Gonzaga"),
    (2025,81,"R3","Columbus Crew","Drew Kerr","FW","USA","Duke"),
    (2025,82,"R3","Inter Miami CF","Michael Appiah","FW","Ghana","FIU"),
    (2025,83,"R3","Atlanta United FC","William Kulvik","DF","Norway","Maryland"),
    (2025,84,"R3","New York City FC","Arnau Farnós","FW","Spain","Oregon State"),
    (2025,85,"R3","Minnesota United FC","Nick Collins","DF","USA","Rutgers"),
    (2025,86,"R3","D.C. United","Grant Bailey","DF","USA","Loyola Chicago"),
    (2025,87,"R3","Orlando City SC","Takahiro Fujita","DF","Japan","Marshall"),
    (2025,88,"R3","New York City FC","Nico Cavallo","DF","USA","UCLA"),
    (2025,89,"R3","Real Salt Lake","Aleksandar Vuković","DF","Serbia","Marshall"),
    (2025,90,"R3","LA Galaxy","Nicklaus Sullivan","FW","USA","CSUSB"),

    # ── 2024 (87 picks, 3 rounds) ──
    (2024,1,"R1","Toronto FC","Tyrese Spicer","FW","Trinidad & Tobago","Lipscomb"),
    (2024,2,"R1","Colorado Rapids","Wayne Frederick","MF","Trinidad & Tobago","Duke"),
    (2024,3,"R1","FC Dallas","Logan Farrington","FW","USA","Oregon State"),
    (2024,4,"R1","Colorado Rapids","Kimani Stewart-Baynes","FW","Canada","Maryland"),
    (2024,5,"R1","Austin FC","Nate Jones","DF","USA","Washington"),
    (2024,6,"R1","Chicago Fire FC","Bryan Dowd","GK","USA","Notre Dame"),
    (2024,7,"R1","D.C. United","Jacob Murrell","FW","USA","Georgetown"),
    (2024,8,"R1","New York City FC","Malachi Jones","FW","Sierra Leone","Lipscomb"),
    (2024,9,"R1","Minnesota United FC","Hugo Bacharach","DF","Spain","Indiana"),
    (2024,10,"R1","CF Montréal","Grayson Doody","DF","USA","UCLA"),
    (2024,11,"R1","Nashville SC","Wyatt Meyer","DF","USA","California"),
    (2024,12,"R1","New York Red Bulls","Aidan O'Connor","DF","USA","Virginia"),
    (2024,13,"R1","San Jose Earthquakes","Jamar Ricketts","DF","USA","Cal State Northridge"),
    (2024,14,"R1","Charlotte FC","Tyger Smalls","FW","England","Loyola Marymount"),
    (2024,15,"R1","Inter Miami CF","Yannick Bright","MF","Italy","New Hampshire"),
    (2024,16,"R1","Real Salt Lake","Matthew Bell","FW","Jamaica","Marshall"),
    (2024,17,"R1","St. Louis City SC","Hosei Kijima","MF","Japan","Wake Forest"),
    (2024,18,"R1","Real Salt Lake","Kevin Bonilla","DF","USA","Portland"),
    (2024,19,"R1","Atlanta United FC","Jayden Hibbert","GK","Jamaica","UConn"),
    (2024,20,"R1","Minnesota United FC","Marcus Caldeira","FW","Canada","West Virginia"),
    (2024,21,"R1","Orlando City SC","Jeorgio Kocevski","MF","USA","Syracuse"),
    (2024,22,"R1","Sporting Kansas City","Ryan Schewe","GK","USA","Georgetown"),
    (2024,23,"R1","Seattle Sounders FC","Kalani Kossa-Rienzi","DF","USA","Washington"),
    (2024,24,"R1","Inter Miami CF","Ryan Carmichael","FW","Northern Ireland","Hofstra"),
    (2024,25,"R1","Orlando City SC","Yutaro Tsukada","FW","Japan","West Virginia"),
    (2024,26,"R1","Houston Dynamo FC","Stephen Annor Gyamfi","FW","Ghana","Virginia"),
    (2024,27,"R1","FC Cincinnati","Brian Schaefer","DF","USA","South Florida"),
    (2024,28,"R1","Los Angeles FC","Jackson Lee","GK","Australia","West Virginia"),
    (2024,29,"R1","Columbus Crew","Jayden Da","FW","USA","Duquesne"),
    (2024,30,"R2","Toronto FC","Joey Maher","DF","USA","Indiana"),
    (2024,31,"R2","Austin FC","Bryant Farkarlun","MF","Liberia","UT Rio Grande Valley"),
    (2024,32,"R2","Inter Miami CF","Leo Afonso","FW","Brazil","Virginia"),
    (2024,33,"R2","Chicago Fire FC","Olu Oyegunle","DF","Canada","Syracuse"),
    (2024,34,"R2","Colorado Rapids","Palmer Ault","MF","USA","Butler"),
    (2024,35,"R2","Chicago Fire FC","Jason Shokalook","FW","USA","Akron"),
    (2024,36,"R2","D.C. United","Brandon Parrish","MF","USA","Clemson"),
    (2024,37,"R2","Real Salt Lake","Damien Barker John","FW","USA","Louisville"),
    (2024,38,"R2","Charlotte FC","Jahlane Forbes","DF","USA","Wake Forest"),
    (2024,39,"R2","CF Montréal","Malik Henry","MF","Canada","Akron"),
    (2024,40,"R2","Portland Timbers","Kyle Linhares","MF","USA","Georgetown"),
    (2024,41,"R2","Charlotte FC","Jacob Babalai","FW","USA","Portland"),
    (2024,42,"R2","San Jose Earthquakes","Beau Leroux","MF","USA","San Jose State"),
    (2024,43,"R2","Colorado Rapids","Anderson Rosa","DF","Brazil","UCF"),
    (2024,44,"R2","FC Dallas","Turner Humphrey","DF","USA","Oregon State"),
    (2024,45,"R2","Vancouver Whitecaps FC","Eliot Goldthorp","DF","England","Hofstra"),
    (2024,46,"R2","LA Galaxy","Ethan Brandt","GK","USA","Western Michigan"),
    (2024,47,"R2","Real Salt Lake","Josh Jones","DF","USA","Louisville"),
    (2024,48,"R2","Atlanta United FC","Javier Armas","DF","Spain","Oregon State"),
    (2024,49,"R2","D.C. United","Aldair Sanchez","DF","USA","North Carolina"),
    (2024,50,"R2","Nashville SC","Kevin Carmichael","DF","USA","California"),
    (2024,51,"R2","Sporting Kansas City","Dyson Clapier","MF","USA","Akron"),
    (2024,52,"R2","Seattle Sounders FC","Antino Lopez","DF","USA","Duke"),
    (2024,53,"R2","Philadelphia Union","Stas Korzeniowski","FW","USA","Penn"),
    (2024,54,"R2","Orlando City SC","Filip Mirkovic","MF","USA","Pittsburgh"),
    (2024,55,"R2","Houston Dynamo FC","Ousmane Sylla","MF","Senegal","Clemson"),
    (2024,56,"R2","FC Cincinnati","Kenji Mboma Dem","FW","France","Dayton"),
    (2024,57,"R2","Los Angeles FC","Kenny Nielsen","DF","USA","Georgetown"),
    (2024,58,"R2","Columbus Crew","Zach Zengue","MF","USA","Georgetown"),
    (2024,59,"R3","Toronto FC","Patrick McDonald","MF","USA","Indiana"),
    (2024,60,"R3","Colorado Rapids","Gunnar Studenhofft","FW","Cayman Islands","Manhattan"),
    (2024,61,"R3","Inter Miami CF","Pep Casas","MF","Spain","UNC-Wilmington"),
    (2024,62,"R3","LA Galaxy","Tucker Lepley","MF","USA","UCLA"),
    (2024,63,"R3","Philadelphia Union","Zachary Bohane","FW","USA","Stanford"),
    (2024,64,"R3","Chicago Fire FC","Laurence Wootton","MF","England","Ohio State"),
    (2024,65,"R3","D.C. United","Nathan Crockford","GK","USA","Wisconsin"),
    (2024,66,"R3","New York City FC","Taylor Calheira","FW","USA","UMBC"),
    (2024,67,"R3","Minnesota United FC","Morris Duggan","DF","Germany","Marshall"),
    (2024,68,"R3","CF Montréal","Eli Conway","FW","USA","UConn"),
    (2024,69,"R3","Portland Timbers","Gage Guerra","FW","USA","Louisville"),
    (2024,70,"R3","Charlotte FC","Nathan Richmond","MF","USA","Clemson"),
    (2024,71,"R3","San Jose Earthquakes","Riley Lynch","FW","USA","Saint Mary's"),
    (2024,72,"R3","Chicago Fire FC","Shane de Flores","MF","USA","Stanford"),
    (2024,73,"R3","FC Dallas","Mads Westergren","DF","Denmark","SMU"),
    (2024,74,"R3","Vancouver Whitecaps FC","Nicolas Fleuriau Chateau","FW","Canada","St. John's"),
    (2024,75,"R3","Nashville SC","Bryce Boneau","MF","USA","Notre Dame"),
    (2024,76,"R3","Real Salt Lake","Maximus Jennings","DF","USA","Georgetown"),
    (2024,77,"R3","Atlanta United FC","Casper Mols","GK","Denmark","Kentucky"),
    (2024,78,"R3","Minnesota United FC","Babacar Niang","MF","Senegal","Wake Forest"),
    (2024,79,"R3","St. Louis City SC","Brendan McSorley","FW","USA","Providence"),
    (2024,80,"R3","Sporting Kansas City","Jonathan Robinson","DF","USA","Western Michigan"),
    (2024,81,"R3","Seattle Sounders FC","Buba Fofanah","FW","Sierra Leone","Portland"),
    (2024,82,"R3","Philadelphia Union","Francesco Montali","GK","USA","Boston"),
    (2024,83,"R3","Orlando City SC","Riyon Tori","MF","Japan","Charlotte"),
    (2024,84,"R3","Real Salt Lake","Ruben Mesalles","DF","USA","Duke"),
    (2024,85,"R3","Toronto FC","Fletcher Bank","MF","USA","Stanford"),
    (2024,86,"R3","CF Montréal","Carson Hodgson","MF","USA","Western Michigan"),
    (2024,87,"R3","Columbus Crew","Luke Pruter","GK","USA","UC Irvine"),

    # ── 2023 (83 picks, 3 rounds) ──
    (2023,1,"R1","Charlotte FC","Hamady Diop","DF","Senegal","Clemson"),
    (2023,2,"R1","Orlando City SC","Shak Mohammed","FW","Ghana","Duke"),
    (2023,3,"R1","Colorado Rapids","Moïse Bombito","DF","Canada","New Hampshire"),
    (2023,4,"R1","New England Revolution","Joshua Bolma","MF","Ghana","Maryland"),
    (2023,5,"R1","Vancouver Whitecaps FC","J.C. Ngando","MF","Cameroon","UNC Greensboro"),
    (2023,6,"R1","Orlando City SC","Duncan McGuire","FW","USA","Creighton"),
    (2023,7,"R1","Real Salt Lake","Ilijah Paul","FW","USA","Washington"),
    (2023,8,"R1","Sporting Kansas City","Stephen Afrifa","FW","Canada","FIU"),
    (2023,9,"R1","St. Louis City SC","Owen O'Malley","MF","USA","Creighton"),
    (2023,10,"R1","San Jose Earthquakes","Daniel Munie","DF","USA","Indiana"),
    (2023,11,"R1","Nashville SC","Joey Skinner","DF","USA","Clemson"),
    (2023,12,"R1","Charlotte FC","Patrick Agyemang","FW","USA","Rhode Island"),
    (2023,13,"R1","Austin FC","CJ Fodrey","FW","USA","San Diego State"),
    (2023,14,"R1","Columbus Crew","Maximilian Arfsten","FW","USA","UC Davis"),
    (2023,15,"R1","Portland Timbers","Noel Caliskan","MF","Germany","Loyola Marymount"),
    (2023,16,"R1","Real Salt Lake","Bertin Jacquesson","FW","France","Pittsburgh"),
    (2023,17,"R1","Orlando City SC","Abdi Salim","DF","Somalia","Syracuse"),
    (2023,18,"R1","Inter Miami CF","Cole Jensen","GK","USA","Xavier"),
    (2023,19,"R1","Minnesota United FC","Ryen Jiba","DF","South Sudan","SLCC"),
    (2023,20,"R1","Austin FC","Valentin Noël","MF","France","Pittsburgh"),
    (2023,21,"R1","New York Red Bulls","Elian Haddock","GK","USA","Yale"),
    (2023,22,"R1","FC Cincinnati","Joey Akpunonu","DF","USA","Bowling Green"),
    (2023,23,"R1","LA Galaxy","Gino Vivi","FW","Costa Rica","Central Florida"),
    (2023,24,"R1","FC Dallas","Herbert Endeley","FW","USA","Indiana"),
    (2023,25,"R1","Real Salt Lake","Emeka Eneli","FW","USA","Cornell"),
    (2023,26,"R1","New York City FC","Malcolm Johnston","MF","Canada","Maryland"),
    (2023,27,"R1","Columbus Crew","Xavier Zengue","DF","USA","Dayton"),
    (2023,28,"R1","Philadelphia Union","Holden Trent","GK","USA","High Point"),
    (2023,29,"R1","Vancouver Whitecaps FC","Levonte Johnson","FW","Canada","Syracuse"),
    (2023,30,"R2","St. Louis City SC","John Klein","MF","USA","Saint Louis"),
    (2023,31,"R2","D.C. United","Ben Stitz","MF","USA","Penn"),
    (2023,32,"R2","Toronto FC","Jalen Watson","DF","Canada","Penn State"),
    (2023,33,"R2","San Jose Earthquakes","Liam Butts","FW","Guyana","Penn State"),
    (2023,34,"R2","Houston Dynamo FC","Isaiah Reid","FW","USA","Clemson"),
    (2023,35,"R2","Nashville SC","Sean Suber","DF","USA","Charlotte"),
    (2023,36,"R2","Atlanta United FC","Tyler Young","MF","USA","Campbell"),
    (2023,37,"R2","Sporting Kansas City","Chris Rindov","DF","USA","Maryland"),
    (2023,38,"R2","Seattle Sounders FC","Eythor Björgolfsson","FW","Norway","Kentucky"),
    (2023,39,"R2","New England Revolution","Victor Souza","DF","USA","Boston College"),
    (2023,40,"R2","Charlotte FC","Nick Scardina","FW","USA","Washington"),
    (2023,41,"R2","Colorado Rapids","Oliver Semmle","GK","Germany","Marshall"),
    (2023,42,"R2","Vancouver Whitecaps FC","Daniel Nimick","DF","Canada","Western Michigan"),
    (2023,43,"R2","Columbus Crew","Clay Holstad","MF","USA","Kentucky"),
    (2023,44,"R2","Portland Timbers","Ryan Bilichuk","GK","USA","Elon"),
    (2023,45,"R2","Real Salt Lake","Amferny Sinclair","MF","Costa Rica","Syracuse"),
    (2023,46,"R2","Orlando City SC","Luis Grassow","DF","Germany","Kentucky"),
    (2023,47,"R2","Inter Miami CF","Bachir Ndiaye","MF","Senegal","UNC Wilmington"),
    (2023,48,"R2","Minnesota United FC","Emmanuel Iwe","MF","Nigeria","St. Cloud State"),
    (2023,49,"R2","Nashville SC","Alex Meinhard","FW","Estonia","Tulsa"),
    (2023,50,"R2","New York Red Bulls","Ethan Conley","DF","USA","UNC Greensboro"),
    (2023,51,"R2","FC Cincinnati","Hunter Morse","GK","USA","Western Michigan"),
    (2023,52,"R2","LA Galaxy","Russell Shealy","GK","USA","Syracuse"),
    (2023,53,"R2","FC Dallas","Ryan Wittenbrink","FW","USA","Indiana"),
    (2023,54,"R2","CF Montréal","Milo Garvanian","DF","USA","North Carolina"),
    (2023,55,"R2","New York City FC","Braudílio Rodrigues","FW","Portugal","Franklin Pierce"),
    (2023,56,"R2","Austin FC","Jackson Wälti","MF","USA","Pittsburgh"),
    (2023,57,"R2","Philadelphia Union","Stefan Stojanovic","FW","USA","Georgetown"),
    (2023,58,"R2","Los Angeles FC","Jassem Koleilat","GK","Czech Republic","New Hampshire"),
    (2023,59,"R3","Seattle Sounders FC","Blake Bowen","DF","USA","San Diego State"),
    (2023,60,"R3","D.C. United","Aidan Rocha","MF","USA","Georgetown"),
    (2023,61,"R3","Toronto FC","Charlie Sharp","FW","USA","Western Michigan"),
    (2023,62,"R3","San Jose Earthquakes","Hunter George","FW","USA","Maryland"),
    (2023,63,"R3","Houston Dynamo FC","Frantz Pierrot","FW","Haiti","Connecticut"),
    (2023,64,"R3","Chicago Fire FC","Noah Egan","DF","USA","Vermont"),
    (2023,65,"R3","Nashville SC","Makel Rasheed","DF","USA","Xavier"),
    (2023,66,"R3","New York City FC","MD Myers","FW","USA","Rutgers"),
    (2023,67,"R3","Chicago Fire FC","Billy Hency","MF","USA","Loyola-Chicago"),
    (2023,68,"R3","New England Revolution","Andreas Ueland","DF","Norway","Virginia"),
    (2023,69,"R3","Charlotte FC","Andrew Privett","MF","USA","Penn State"),
    (2023,71,"R3","Vancouver Whitecaps FC","Buster Sjöberg","DF","Sweden","Syracuse"),
    (2023,72,"R3","Austin FC","Salvatore Mazzaferro","DF","Canada","South Florida"),
    (2023,73,"R3","Portland Timbers","Jaden Jones-Riley","DF","USA","Dayton"),
    (2023,74,"R3","Real Salt Lake","Moses Mensah","DF","Ghana","Campbell"),
    (2023,75,"R3","CF Montréal","Ousman Jabang","DF","USA","Mercer"),
    (2023,76,"R3","Chicago Fire FC","Wilmer Cabrera Jr.","FW","Colombia","Butler"),
    (2023,78,"R3","Nashville SC","Rory O'Driscoll","MF","USA","New Hampshire"),
    (2023,79,"R3","New York Red Bulls","Amos Shapiro-Thompson","MF","USA","Boston College"),
    (2023,80,"R3","FC Cincinnati","London Aghedo","DF","USA","Air Force"),
    (2023,82,"R3","FC Dallas","Kameron Lacey","FW","Jamaica","Charlotte"),
    (2023,83,"R3","CF Montréal","Nick Christoffersen","GK","Canada","Penn"),
    (2023,84,"R3","Nashville SC","Lyam MacKinnon","FW","Switzerland","Villanova"),
    (2023,85,"R3","Portland Timbers","Tyler Clegg","DF","USA","James Madison"),
    (2023,87,"R3","Los Angeles FC","Noah Dollenmayer","DF","USA","Cal State San Bernardino"),

    # ── 2022 (84 picks, 3 rounds + comp) ──
    (2022,1,"R1","Charlotte FC","Ben Bender","MF","USA","Maryland"),
    (2022,2,"R1","FC Cincinnati","Roman Celentano","GK","USA","Indiana"),
    (2022,3,"R1","FC Dallas","Isaiah Parker","FW","USA","Saint Louis"),
    (2022,4,"R1","Houston Dynamo","Thorleifur Úlfarsson","FW","Iceland","Duke"),
    (2022,5,"R1","Austin FC","Kipp Keller","DF","USA","Saint Louis"),
    (2022,6,"R1","FC Dallas","Lucas Bartlett","DF","USA","St. John's"),
    (2022,7,"R1","NY Red Bulls","Matt Nocita","DF","USA","Naval Academy"),
    (2022,8,"R1","San Jose Earthquakes","Ousseni Bouda","FW","Burkina Faso","Stanford"),
    (2022,9,"R1","Inter Miami CF","Ryan Sailor","DF","USA","Washington"),
    (2022,10,"R1","Nashville SC","Ahmed Longmire","DF","USA","UCLA"),
    (2022,11,"R1","Chicago Fire FC","Kendall Burks","DF","USA","Washington"),
    (2022,12,"R1","Columbus Crew","Patrick Schulte","GK","USA","Saint Louis"),
    (2022,13,"R1","San Jose Earthquakes","Oskar Ågren","DF","Sweden","Clemson"),
    (2022,14,"R1","FC Cincinnati","Ian Murphy","DF","USA","Duke"),
    (2022,15,"R1","CF Montréal","Jojea Kwizera","FW","DR Congo","Utah Valley"),
    (2022,16,"R1","Vancouver Whitecaps FC","Simon Becher","FW","USA","Saint Louis"),
    (2022,17,"R1","Minnesota United FC","Tani Oluwaseyi","FW","Canada","St. John's"),
    (2022,18,"R1","Orlando City SC","Jack Lynn","FW","USA","Notre Dame"),
    (2022,19,"R1","Atlanta United FC","Erik Centeno","FW","USA","Pacific"),
    (2022,20,"R1","NY Red Bulls","O'Vonte Mullings","FW","Canada","Florida Gulf Coast"),
    (2022,21,"R1","LA Galaxy","Farai Mutatu","FW","Zimbabwe","Michigan State"),
    (2022,22,"R1","Sporting Kansas City","Esai Easley","DF","USA","Grand Canyon"),
    (2022,23,"R1","Colorado Rapids","Mohamed Omar","MF","Somalia","Notre Dame"),
    (2022,24,"R1","New England Revolution","Jacob Jackson","GK","USA","Loyola Marymount"),
    (2022,25,"R1","Columbus Crew","Philip Quinton","DF","USA","Notre Dame"),
    (2022,26,"R1","Colorado Rapids","Anthony Markanich","DF","USA","Northern Illinois"),
    (2022,27,"R1","Portland Timbers","Justin Rasmussen","MF","USA","Grand Canyon"),
    (2022,28,"R1","FC Dallas","Tsiki Ntsabeleng","FW","South Africa","Oregon State"),
    (2022,29,"R2","Charlotte FC","Kyle Holcomb","FW","USA","Wake Forest"),
    (2022,30,"R2","FC Cincinnati","Nick Markanich","FW","USA","Northern Illinois"),
    (2022,31,"R2","Toronto FC","Luka Gavran","GK","Canada","St. John's"),
    (2022,32,"R2","Houston Dynamo","Paulo Lima","MF","Portugal","Providence"),
    (2022,33,"R2","Chicago Fire FC","Charlie Ostrem","DF","USA","Washington"),
    (2022,34,"R2","New York City FC","Kevin O'Toole","FW","Ireland","Princeton"),
    (2022,35,"R2","Austin FC","Charlie Asensio","DF","USA","Clemson"),
    (2022,36,"R2","D.C. United","Sofiane Djeffal","MF","France","Oregon State"),
    (2022,37,"R2","Inter Miami CF","Lucas Meek","FW","USA","Washington"),
    (2022,38,"R2","Nashville SC","Will Meyer","GK","USA","Akron"),
    (2022,39,"R2","Houston Dynamo","Arturo Ordoñez","DF","Spain","Pittsburgh"),
    (2022,40,"R2","Columbus Crew","Jacob Erlandson","DF","USA","Bowling Green"),
    (2022,41,"R2","D.C. United","Alex Nagy","MF","USA","Vermont"),
    (2022,42,"R2","LA Galaxy","Callum Johnson","MF","USA","Clemson"),
    (2022,43,"R2","Seattle Sounders FC","Achille Robin","DF","France","Washington"),
    (2022,44,"R2","Vancouver Whitecaps FC","Luis Felipe Fernandez-Salvador","MF","Ecuador","Clemson"),
    (2022,45,"R2","Colorado Rapids","Roberto Molina","MF","El Salvador","UC Irvine"),
    (2022,46,"R2","Orlando City SC","Nathan Dossantos","DF","Canada","Marshall"),
    (2022,47,"R2","Atlanta United FC","Tristan Trager","FW","USA","Air Force"),
    (2022,48,"R2","Inter Miami CF","Justin Ingram","MF","USA","Loyola (MD)"),
    (2022,49,"R2","Vancouver Whitecaps FC","Giovanni Aguilar","MF","USA","Cal State Northridge"),
    (2022,50,"R2","Sporting Kansas City","Brett St. Martin","DF","USA","Maryland"),
    (2022,52,"R2","New England Revolution","Ben Reveno","DF","USA","UCLA"),
    (2022,53,"R2","Real Salt Lake","Pedro Fonseca","FW","Brazil","Louisville"),
    (2022,54,"R2","Inter Miami CF","Tyler Bagley","MF","USA","Cornell"),
    (2022,55,"R2","Portland Timbers","Julian Bravo","DF","USA","Santa Clara"),
    (2022,56,"R2","New York City FC","Kingsford Adjei","FW","Ghana","Dayton"),
    (2022,57,"R3","Charlotte FC","George Marks","GK","USA","Clemson"),
    (2022,59,"R3","Toronto FC","Reshaun Walkes","FW","Canada","UT Rio Grande Valley"),
    (2022,60,"R3","LA Galaxy","Chandler Vaughn","DF","USA","Saint Louis"),
    (2022,61,"R3","Austin FC","Michael Knapp","MF","USA","Montclair State"),
    (2022,62,"R3","FC Dallas","Alec Smir","GK","USA","North Carolina"),
    (2022,63,"R3","Chicago Fire FC","Carlo Ritaccio","DF","USA","Akron"),
    (2022,64,"R3","San Jose Earthquakes","John Martin","MF","USA","Clemson"),
    (2022,66,"R3","FC Dallas","Chase Niece","DF","USA","Saint Louis"),
    (2022,67,"R3","CF Montréal","Ivy Brisma","FW","Haiti","NC State"),
    (2022,68,"R3","Columbus Crew","Chris Donovan","FW","USA","Drexel"),
    (2022,69,"R3","D.C. United","Skage Simonsen","MF","Norway","SMU"),
    (2022,71,"R3","NY Red Bulls","Giannis Nikopolidis","GK","Greece","Georgetown"),
    (2022,72,"R3","Vancouver Whitecaps FC","Théo Collomb","FW","France","UNC Greensboro"),
    (2022,73,"R3","NY Red Bulls","Seth Kuhn","MF","USA","Penn State"),
    (2022,74,"R3","Orlando City SC","Nick Taylor","FW","Cambodia","UCF"),
    (2022,75,"R3","Atlanta United FC","Daniel Bloyou","FW","Ghana","Penn State"),
    (2022,76,"R3","Seattle Sounders FC","Hal Uderitz","MF","USA","Seattle"),
    (2022,81,"R3","Real Salt Lake","Jasper Löffelsend","DF","Germany","Pittsburgh"),
    (2022,83,"R3","Portland Timbers","Sivert Haugli","DF","Norway","Virginia Tech"),
    (2022,84,"R3","New York City FC","El Mahdi Youssoufi","FW","Morocco","St. Francis Brooklyn"),
    (2022,85,"Comp","Chicago Fire FC","Yanis Leerman","DF","France","UCF"),
    (2022,86,"Comp","Vancouver Whitecaps FC","Vitor Dias","MF","Brazil","Marshall"),
    (2022,87,"Comp","FC Dallas","Holland Rula","DF","USA","Wake Forest"),
    (2022,88,"Comp","Atlanta United FC","Tola Showunmi","FW","England","New Hampshire"),

    # ── 2021 (76 picks, 3 rounds + comp) ──
    (2021,1,"R1","Austin FC","Daniel Pereira","MF","Venezuela","Virginia Tech"),
    (2021,2,"R1","FC Cincinnati","Calvin Harris","FW","England","Wake Forest"),
    (2021,3,"R1","Colorado Rapids","Philip Mayaka","MF","Kenya","Clemson"),
    (2021,4,"R1","D.C. United","Kimarni Smith","FW","England","Clemson"),
    (2021,5,"R1","D.C. United","Michael DeShields","DF","USA","Wake Forest"),
    (2021,6,"R1","Houston Dynamo","Ethan Bartlow","DF","USA","Washington"),
    (2021,7,"R1","Real Salt Lake","Bret Halsey","DF","USA","Virginia"),
    (2021,8,"R1","Orlando City SC","Derek Dodson","FW","USA","Georgetown"),
    (2021,9,"R1","Vancouver Whitecaps","David Egbo","FW","Nigeria","Akron"),
    (2021,10,"R1","Inter Miami CF","Josh Penn","FW","USA","Indiana"),
    (2021,11,"R1","Austin FC","Freddy Kleemann","DF","USA","Washington"),
    (2021,12,"R1","San Jose Earthquakes","Thomas Williamson","FW","USA","California"),
    (2021,13,"R1","NY Red Bulls","Luther Archimède","FW","Guadeloupe","Syracuse"),
    (2021,14,"R1","Los Angeles FC","Danny Trejo","FW","Mexico","CSUN"),
    (2021,15,"R1","FC Dallas","Nicky Hernandez","MF","USA","SMU"),
    (2021,16,"R1","LA Galaxy","Josh Drack","FW","USA","Denver"),
    (2021,17,"R1","Minnesota United","Justin McMaster","FW","Jamaica","Wake Forest"),
    (2021,18,"R1","Minnesota United","Nabilai Kibunguchy","DF","USA","UC Davis"),
    (2021,19,"R1","Orlando City SC","Rio Hope-Gund","DF","USA","Georgetown"),
    (2021,20,"R1","Nashville SC","Irakoze Donasiyano","MF","Burundi","Virginia"),
    (2021,21,"R1","Austin FC","Aedan Stanley","DF","USA","Duke"),
    (2021,22,"R1","Orlando City SC","Brandon Hackenberg","DF","USA","Penn State"),
    (2021,23,"R1","Vancouver Whitecaps","Javain Brown","DF","Jamaica","South Florida"),
    (2021,24,"R1","New England Revolution","Edward Kizza","FW","Uganda","Pittsburgh"),
    (2021,25,"R1","Toronto FC","Matt Di Rosa","MF","USA","Maryland"),
    (2021,26,"R1","Inter Miami CF","Aimé Mabika","DF","Zambia","Kentucky"),
    (2021,27,"R1","Columbus Crew","Justin Malou","DF","Senegal","Clemson"),
    (2021,28,"R2","Austin FC","Daniel Steedman","MF","Scotland","Virginia"),
    (2021,29,"R2","FC Cincinnati","Avionne Flanagan","DF","USA","South Florida"),
    (2021,30,"R2","Houston Dynamo","Kristo Strickler","FW","USA","Virginia Tech"),
    (2021,31,"R2","Atlanta United","Josh Bauer","DF","USA","New Hampshire"),
    (2021,32,"R2","D.C. United","Logan Panchot","DF","USA","Stanford"),
    (2021,33,"R2","Chicago Fire","Jackson Ragen","DF","USA","Michigan"),
    (2021,34,"R2","Real Salt Lake","Elijah Amo","MF","USA","Louisville"),
    (2021,35,"R2","LA Galaxy","Preston Judd","FW","USA","Denver"),
    (2021,36,"R2","Nashville SC","Tom Judge","DF","USA","James Madison"),
    (2021,37,"R2","Inter Miami CF","Joe Hafferty","DF","USA","Oregon State"),
    (2021,38,"R2","Minnesota United","Sean O'Hearn","DF","USA","Georgetown"),
    (2021,39,"R2","San Jose Earthquakes","George Asomani","MF","Ghana","NC State"),
    (2021,40,"R2","NY Red Bulls","Lamine Conte","DF","Guinea","Louisville"),
    (2021,41,"R2","Los Angeles FC","CC Uche","DF","USA","Ohio State"),
    (2021,43,"R2","Portland Timbers","Dawson McCartney","MF","USA","Dartmouth"),
    (2021,44,"R2","New York City FC","Ben Di Rosa","DF","USA","Maryland"),
    (2021,45,"R2","Toronto FC","Nathaniel Crofts","FW","England","Virginia"),
    (2021,46,"R2","Vancouver Whitecaps","Eric Iloski","MF","USA","UCLA"),
    (2021,47,"R2","Chicago Fire","Christian Pinzón","FW","USA","Cal State Fullerton"),
    (2021,48,"R2","FC Dallas","Colin Shutler","GK","USA","Virginia"),
    (2021,49,"R2","Orlando City SC","Andrew Pannenberg","GK","USA","Wake Forest"),
    (2021,50,"R2","Sporting Kansas City","Matt Constant","DF","Canada","North Carolina"),
    (2021,51,"R2","New England Revolution","Francois Dulysse","DF","Haiti","Manhattan College"),
    (2021,52,"R2","Columbus Crew","Joshua Jackson-Ketchup","DF","USA","Ohio State"),
    (2021,53,"R2","Vancouver Whitecaps","Joel Harrison","DF","Canada","Michigan"),
    (2021,54,"R2","FC Cincinnati","Jonas Fjeldberg","MF","Norway","Dayton"),
    (2021,55,"R3","Austin FC","Noah Lawrence","GK","USA","Ohio State"),
    (2021,56,"R3","FC Cincinnati","Matthew Vowinkel","FW","USA","Hofstra"),
    (2021,57,"R3","Houston Dynamo","Brandon Terwege","DF","USA","SMU"),
    (2021,59,"R3","Atlanta United","Aiden McFadden","MF","USA","Notre Dame"),
    (2021,60,"R3","Chicago Fire","Mitch Guitar","MF","USA","Wisconsin"),
    (2021,61,"R3","Real Salt Lake","Aris Briggs","FW","USA","Georgia State"),
    (2021,63,"R3","CF Montréal","Giuseppe Barone","MF","USA","Michigan State"),
    (2021,64,"R3","Toronto FC","Paul Rothrock","MF","USA","Georgetown"),
    (2021,67,"R3","NY Red Bulls","AJ Marcucci","GK","USA","Connecticut College"),
    (2021,68,"R3","Los Angeles FC","Alvaro Quezada","FW","USA","UC Irvine"),
    (2021,70,"R3","Portland Timbers","Diego Gutierrez","FW","USA","Creighton"),
    (2021,71,"R3","New York City FC","Vuk Latinovich","MF","Serbia","Milwaukee"),
    (2021,72,"R3","Toronto FC","Talen Maples","DF","Canada","SMU"),
    (2021,73,"R3","Nashville SC","Sondre Norheim","DF","Norway","Syracuse"),
    (2021,74,"R3","Nashville SC","Tor Saunders","GK","USA","Coastal Carolina"),
    (2021,75,"R3","FC Dallas","Thibaut Jacquel","FW","France","Campbell"),
    (2021,76,"R3","FC Dallas","Mark Salas","DF","USA","North Carolina"),
    (2021,77,"R3","Sporting Kansas City","Jamil Roberts","FW","England","Marshall"),
    (2021,80,"R3","Seattle Sounders","TJ Bush","GK","USA","James Madison"),
    (2021,84,"Comp","Real Salt Lake","Rene White","FW","USA","NJIT"),
    (2021,86,"Comp","Nashville SC","Leroy Enzugusi","FW","Kenya","Drake"),

    # ── 2020 (77 picks, 4 rounds) ──
    (2020,1,"R1","Inter Miami CF","Robbie Robinson","FW","USA","Clemson"),
    (2020,2,"R1","Nashville SC","Jack Maher","DF","USA","Indiana"),
    (2020,3,"R1","Inter Miami CF","Dylan Nealis","MF","USA","Georgetown"),
    (2020,4,"R1","Vancouver WFC","Ryan Raposo","MF","Canada","Syracuse"),
    (2020,5,"R1","Orlando City SC","Daryl Dike","FW","USA","Virginia"),
    (2020,6,"R1","New England Revolution","Henry Kessler","DF","USA","Virginia"),
    (2020,7,"R1","Columbus Crew","Miguel Berry","FW","Spain","San Diego"),
    (2020,8,"R1","Houston Dynamo","Garrett McLaughlin","FW","USA","SMU"),
    (2020,9,"R1","Montreal Impact","Jeremy Kelly","MF","USA","North Carolina"),
    (2020,10,"R1","NY Red Bulls","Patrick Seagrist","DF","USA","Marquette"),
    (2020,11,"R1","Nashville SC","Alistair Johnston","MF","Canada","Wake Forest"),
    (2020,12,"R1","San Jose Earthquakes","Tanner Beason","DF","USA","Stanford"),
    (2020,13,"R1","Nashville SC","Elliot Panicco","GK","USA","Charlotte"),
    (2020,14,"R1","FC Dallas","Nkosi Tafari","DF","USA","Seattle"),
    (2020,15,"R1","NY Red Bulls","Cherif Dieye","MF","Senegal","Louisville"),
    (2020,16,"R1","Portland Timbers","Aaron Molloy","MF","Ireland","Penn State"),
    (2020,17,"R1","FC Dallas","Cal Jennings","FW","USA","UCF"),
    (2020,18,"R1","Minnesota United FC","Noah Billingsley","DF","New Zealand","UC Santa Barbara"),
    (2020,19,"R1","Toronto FC","Nyal Higgins","DF","Canada","Syracuse"),
    (2020,20,"R1","Real Salt Lake","Dayonn Harris","MF","Canada","UConn"),
    (2020,21,"R1","D.C. United","Simon Lefebvre","GK","France","Temple"),
    (2020,22,"R1","New York City FC","Jesus Perez","MF","USA","UIC"),
    (2020,23,"R1","Atlanta United FC","Patrick Nielsen","DF","Denmark","Michigan State"),
    (2020,24,"R1","Los Angeles FC","Paulo Pita","GK","Brazil","Marshall"),
    (2020,25,"R1","Toronto FC","Ifunanyachi Achara","FW","Nigeria","Georgetown"),
    (2020,26,"R1","Chicago Fire FC","Jonathan Jimenez","DF","Trinidad & Tobago","Pacific"),
    (2020,27,"R2","San Jose Earthquakes","Jack Skahan","MF","USA","North Carolina"),
    (2020,28,"R2","Nashville SC","Tanner Dieterich","MF","USA","Clemson"),
    (2020,29,"R2","FC Cincinnati","Rey Ortiz","FW","USA","Portland"),
    (2020,30,"R2","New England Revolution","Simon Lekressner","DF","USA","California"),
    (2020,31,"R2","Orlando City SC","Joey DeZart","MF","Jamaica","Wake Forest"),
    (2020,32,"R2","Vancouver WFC","Daniel Gagliardi","GK","USA","FIU"),
    (2020,33,"R2","Toronto FC","Malick Mbaye","DF","Senegal","Clemson"),
    (2020,34,"R2","Houston Dynamo","Luka Prpa","MF","USA","Marquette"),
    (2020,35,"R2","Seattle Sounders FC","Danny Reynolds","DF","England","UNC Wilmington"),
    (2020,36,"R2","NY Red Bulls","Wallis Lapsley","GK","USA","UC Davis"),
    (2020,37,"R2","Colorado Rapids","Robin Afamefuna","DF","Germany","Virginia"),
    (2020,38,"R2","San Jose Earthquakes","Jon Bell","DF","USA","UMBC"),
    (2020,39,"R2","Orlando City SC","Jonathan Dean","DF","USA","UCF"),
    (2020,40,"R2","FC Dallas","Manuel Ferriol","MF","Spain","James Madison"),
    (2020,41,"R2","NY Red Bulls","Deri Corfe","FW","England","Wright State"),
    (2020,42,"R2","D.C. United","Josh Fawole","FW","USA","Loyola (MD)"),
    (2020,43,"R2","New England Revolution","Keegan Meyer","GK","USA","High Point"),
    (2020,44,"R2","Orlando City SC","Austin Aviza","GK","USA","Providence"),
    (2020,45,"R2","LA Galaxy","Tom Smart","DF","Northern Ireland","Akron"),
    (2020,46,"R2","Real Salt Lake","Michael Wetungu","DF","USA","Michigan State"),
    (2020,47,"R2","Columbus Crew","Remi Prieur","GK","USA","Saint Mary's"),
    (2020,48,"R2","New York City FC","Félicien Dumas","DF","France","Notre Dame"),
    (2020,49,"R2","Columbus Crew","Danny Griffin","MF","USA","Providence"),
    (2020,50,"R2","Los Angeles FC","Jack Hallahan","MF","Ireland","Michigan"),
    (2020,51,"R2","Toronto FC","Simon Wæver","DF","Denmark","Indiana"),
    (2020,52,"R2","Seattle Sounders FC","Timo Mehlich","MF","Germany","UNLV"),
    (2020,53,"R3","FC Cincinnati","Joris Ahlinvi","MF","Benin","Indiana"),
    (2020,54,"R3","Nashville SC","Shak Adams","FW","St. Vincent & Grenadines","Florida Gulf Coast"),
    (2020,57,"R3","Orlando City SC","Nick O'Callaghan","DF","USA","FIU"),
    (2020,58,"R3","Sporting Kansas City","Jaret Townsend","MF","USA","Washington"),
    (2020,59,"R3","Columbus Crew","Ryo Shimazaki","DF","Japan","VCU"),
    (2020,62,"R3","NY Red Bulls","Stavros Zarokostas","FW","Greece","Rhode Island"),
    (2020,65,"R3","D.C. United","Andrew Verdi","GK","USA","Michigan"),
    (2020,66,"R3","FC Dallas","Derek Waldeck","MF","USA","Stanford"),
    (2020,67,"R3","NY Red Bulls","Barry Sharifi","MF","USA","Loyola (MD)"),
    (2020,68,"R3","Portland Timbers","Zac McGraw","DF","Canada","West Point"),
    (2020,70,"R3","Houston Dynamo","Duncan Turnbull","GK","USA","Notre Dame"),
    (2020,74,"R3","New York City FC","Parker Siegfried","GK","USA","Ohio State"),
    (2020,75,"R3","Atlanta United FC","Phillip Goodrum","FW","USA","UNC Wilmington"),
    (2020,76,"R3","Los Angeles FC","Jorge González","MF","Spain","SIUE"),
    (2020,78,"R3","Seattle Sounders FC","Julian Avila-Good","MF","Canada","Seattle"),
    (2020,79,"R4","FC Dallas","Anders Engebretsen","FW","Norway","Saint Mary's"),
    (2020,80,"R4","Nashville SC","Luke Haakenson","MF","USA","Creighton"),
    (2020,84,"R4","Sporting Kansas City","James Kasak","DF","USA","Virginia Tech"),
    (2020,86,"R4","Houston Dynamo","Kyle Edwards","FW","St. Vincent & Grenadines","UTRGV"),
    (2020,88,"R4","Minnesota United FC","Matt Bentley","FW","England","Missouri State"),
    (2020,92,"R4","FC Dallas","Aidan Megally","MF","USA","Loyola Chicago"),
    (2020,93,"R4","NY Red Bulls","Niko Petridis","MF","USA","St. John's"),
    (2020,94,"R4","Portland Timbers","Joergen Oland","DF","Norway","Fordham"),
    (2020,96,"R4","Minnesota United FC","Andrew Booth","MF","Jamaica","FIU"),
    (2020,102,"R4","Los Angeles FC","Younes Boudadi","DF","Morocco","Creighton"),
]


def save_draft_csv():
    headers = ["year","overall_pick","round","team_drafted","player_name","position","nationality","college"]
    out_path = os.path.join(DATA_DIR, "mls_draft_picks_2020_2025.csv")
    with open(out_path, "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(headers)
        for row in DRAFT_PICKS:
            w.writerow(row)
    print(f"Saved {len(DRAFT_PICKS)} picks → {out_path}")
    return out_path


def summarize_by_year():
    by_year = defaultdict(list)
    for pick in DRAFT_PICKS:
        by_year[pick[0]].append(pick)
    print("\n=== Picks by year ===")
    total = 0
    for yr in sorted(by_year):
        n = len(by_year[yr])
        total += n
        print(f"  {yr}: {n} picks")
    print(f"  TOTAL: {total} picks (2020-2025)")


def summarize_nationality():
    usa = sum(1 for p in DRAFT_PICKS if p[6] == "USA")
    intl = len(DRAFT_PICKS) - usa
    print(f"\n=== Nationality ===")
    print(f"  US players: {usa} ({usa/len(DRAFT_PICKS)*100:.1f}%)")
    print(f"  International: {intl} ({intl/len(DRAFT_PICKS)*100:.1f}%)")


def summarize_round():
    by_round = defaultdict(int)
    for p in DRAFT_PICKS:
        by_round[p[2]] += 1
    print("\n=== By round ===")
    for r in ["R1","R2","R3","R4","Comp"]:
        if by_round[r]:
            print(f"  {r}: {by_round[r]}")


def top_colleges():
    from collections import Counter
    colleges = Counter(p[7] for p in DRAFT_PICKS)
    print("\n=== Top 15 colleges (2020-2025 combined) ===")
    for college, n in colleges.most_common(15):
        print(f"  {college}: {n}")


if __name__ == "__main__":
    path = save_draft_csv()
    summarize_by_year()
    summarize_nationality()
    summarize_round()
    top_colleges()

    print("\n--- Next step ---")
    print("To compute survival rates, provide 2026 active MLS roster data.")
    print("Paste FBRef draft pages (they show 'Current Team' column) OR")
    print("provide MLSPA 2026 salary guide player list.")
    print("Script will cross-reference player names against active roster list.")
