#!/usr/bin/env python3
"""
Build EDP (Elite Development Program) Soccer clubs CSV.
Data sourced from myclubscout.com/leagues/edp-soccer (ClubScout directory).
EDP is a competitive travel league primarily in NJ/PA/MD/CT/NY/VA, 249 clubs, 28 states.
Output: data/edp_clubs.csv
"""

import csv, os
from collections import Counter

DATA_DIR = "data"

# (club_name, city, state) — deduplicated from ClubScout directory
EDP_CLUBS = [
    ("A3 Soccer",                               "Edison",                "NJ"),
    ("AC Delray",                               "Delray Beach",          "FL"),
    ("Academia Doral Soccer Club",              "Doral",                 "FL"),
    ("Ajax Premier CT",                         "Unknown",               "CT"),
    ("ALBION SC Delaware",                      "Unknown",               "DE"),
    ("Alexandria SA",                           "Alexandria",            "VA"),
    ("American Soccer Club of NJ",              "Newark",                "NJ"),
    ("Anthracite FC",                           "Tamaqua",               "PA"),
    ("Atletico de Madrid Academia Miami",       "Miami",                 "FL"),
    ("Back Mountain Surf",                      "Dallas",                "PA"),
    ("Baltimore Armour",                        "Baltimore",             "MD"),
    ("Baltimore Bays Soccer Club",              "Baltimore",             "MD"),
    ("Baltimore Celtic Soccer Club",            "Baltimore",             "MD"),
    ("Baltimore Stars FC",                      "Baltimore",             "MD"),
    ("Barca Academy Orlando",                   "Orlando",               "FL"),
    ("BARCA Academy Pro Miami",                 "Miami",                 "FL"),
    ("Barcelona SC NYC",                        "Woodhaven",             "NY"),
    ("Bayonne Youth Soccer Association",        "Bayonne",               "NJ"),
    ("Bayshore Soccer Club",                    "Middletown",            "NJ"),
    ("Beachside SC",                            "Unknown",               "CT"),
    ("Beachside SC North",                      "Unknown",               "CT"),
    ("Bensalem Soccer Academy",                 "Bensalem",              "PA"),
    ("Bergenfield United SC",                   "Bergenfield",           "NJ"),
    ("Berkeley Heights Youth Soccer Club",      "Berkeley Heights",      "NJ"),
    ("BEST FC Soccer Club",                     "Northborough",          "MA"),
    ("Bethesda SC",                             "Bethesda",              "MD"),
    ("Bloomfield SC",                           "Bloomfield",            "NJ"),
    ("Blue Mountain SC",                        "Orwigsburg",            "PA"),
    ("Bordentown FC",                           "Bordentown",            "NJ"),
    ("Branchburg Travel SC",                    "Branchburg",            "NJ"),
    ("Brewster FC",                             "Brewster",              "NY"),
    ("Brick Township SA",                       "Brick",                 "NJ"),
    ("Bridgewater SA",                          "Bridgewater",           "NJ"),
    ("Brooklyn Italians SC",                    "Brooklyn",              "NY"),
    ("Buckingham United Soccer Club",           "Doylestown",            "PA"),
    ("Camp Hill SC",                            "Camp Hill",             "PA"),
    ("Cedar Stars Academy",                     "Carlstadt",             "NJ"),
    ("Cedar Stars Academy - Monmouth",          "Tinton Falls",          "NJ"),
    ("Cedar Stars Academy (Staten Island)",     "Staten Island",         "NY"),
    ("Centercourt FC",                          "Unknown",               "NJ"),
    ("Central Jersey Futbol Alliance",          "Monroe Township",       "NJ"),
    ("Central Susquehanna SC",                  "Lewisburg",             "PA"),
    ("CFC North",                               "Newtown",               "CT"),
    ("Chatham United SA",                       "Chatham",               "NJ"),
    ("Chelsea Piers Soccer Club",               "Stamford",              "CT"),
    ("Cherry Hill FC",                          "Cherry Hill",           "NJ"),
    ("Cherry Hill SC",                          "Cherry Hill",           "NJ"),
    ("Cheshire Soccer Academy",                 "Cheshire",              "CT"),
    ("Chestnut Hill Soccer Club",               "Philadelphia",          "PA"),
    ("Cinnaminson SC",                          "Cinnaminson",           "NJ"),
    ("Clark SC",                                "Clark",                 "NJ"),
    ("Clifton United FC",                       "Clifton",               "NJ"),
    ("Colonia Youth Soccer Association",        "Colonia",               "NJ"),
    ("Colts Neck",                              "Colts Neck",            "NJ"),
    ("Community SC",                            "Linden",                "NJ"),
    ("Connetquot United Soccer Club",           "Bohemia",               "NY"),
    ("Coppermine SC",                           "Baltimore",             "MD"),
    ("Coventry SA",                             "Pottstown",             "PA"),
    ("Cranbury Soccer Club",                    "Cranbury",              "NJ"),
    ("Cranford SC",                             "Cranford",              "NJ"),
    ("CSB Youth Soccer Club",                   "Brooklyn",              "NY"),
    ("CT Rush",                                 "Glastonbury",           "CT"),
    ("Dallastown Soccer Club",                  "York",                  "PA"),
    ("Danubia SC",                              "Astoria",               "NY"),
    ("Delaware Football Club",                  "Unknown",               "DE"),
    ("Delaware Futbol Academy",                 "Unknown",               "DE"),
    ("Deptford FC",                             "Deptford",              "NJ"),
    ("Dillsburg Area SC",                       "Dillsburg",             "PA"),
    ("East Brunswick Soccer Club",              "East Brunswick",        "NJ"),
    ("East Greenwich SA",                       "East Greenwich",        "RI"),
    ("East Hanover Soccer Club",                "East Hanover",          "NJ"),
    ("East Penn SC",                            "Emmaus",                "PA"),
    ("East Ramapo",                             "Spring Valley",         "NY"),
    ("East Windsor PAL",                        "East Windsor",          "NJ"),
    ("Edison United SA",                        "Edison",                "NJ"),
    ("Egg Harbor Township SC",                  "Egg Harbor Township",   "NJ"),
    ("Elite Academy Jupiter",                   "Jupiter",               "FL"),
    ("Elite Soccer Club Plainfield",            "Plainfield",            "NJ"),
    ("Elizabeth Youth Soccer",                  "Elizabeth",             "NJ"),
    ("Elmwood Park Crew Soccer Club",           "Elmwood Park",          "NJ"),
    ("ENCO United Soccer Club",                 "Easton",                "PA"),
    ("Ephrata Youth SC",                        "Ephrata",               "PA"),
    ("Europa Lions FC",                         "Waldwick",              "NY"),
    ("Fairfield United SA",                     "Fairfield",             "CT"),
    ("Fairfield Youth Soccer Club",             "Fairfield",             "CT"),
    ("Falls SC",                                "Levittown",             "PA"),
    ("FC Ballyhoo",                             "Flemington",            "NJ"),
    ("FC Berna Legacy",                         "Garfield",              "NJ"),
    ("FC Brasil",                               "Newark",                "NJ"),
    ("FC Copa Academy",                         "Hillsborough Township", "NJ"),
    ("FC DELCO",                                "Wayne",                 "PA"),
    ("FC Dutchmen Premier",                     "Schenectady",           "NY"),
    ("FC Montco",                               "Lansdale",              "PA"),
    ("FC Neshanic",                             "Neshanic Station",      "NJ"),
    ("FC Pocono",                               "East Stroudsburg",      "PA"),
    ("FC Somers",                               "Somers",                "NY"),
    ("FC Virginia",                             "Richmond",              "VA"),
    ("Fever SC",                                "Woodbridge",            "NJ"),
    ("Florham Park Soccer Club",                "Florham Park",          "NJ"),
    ("Florida Legends FC",                      "Unknown",               "FL"),
    ("Fort Lee Soccer League",                  "Fort Lee",              "NJ"),
    ("Franklin Township SC",                    "Franklin Township",     "NJ"),
    ("Franklin TWP Youth Soccer",               "Newfield",              "NJ"),
    ("Freehold SL",                             "Freehold",              "NJ"),
    ("Futbol Total Academy NJ",                 "North Plainfield",      "NJ"),
    ("Future Soccer Academy",                   "Ridgefield Park",       "NY"),
    ("Gettysburg Youth Soccer Club",            "Gettysburg",            "PA"),
    ("Hamilton Soccer Club",                    "Allentown",             "NJ"),
    ("Hammonton YSA",                           "Hammonton",             "NJ"),
    ("Hanover Soccer Club (NJ)",                "Hanover",               "NJ"),
    ("Harford FC United",                       "Forest Hill",           "MD"),
    ("Harrison SC",                             "Harrison",              "NJ"),
    ("Haverford SC",                            "Havertown",             "PA"),
    ("Hazlet United",                           "Hazlet",                "NJ"),
    ("Hempstead EOC",                           "Hempstead",             "NY"),
    ("Hershey SC",                              "Hershey",               "PA"),
    ("HEX FC",                                  "Hackensack",            "NJ"),
    ("Higher Level",                            "East Greenwich",        "RI"),
    ("Highland Youth Soccer Club",              "Sicklerville",          "NJ"),
    ("Hillsborough SC",                         "Hillsborough",          "NJ"),
    ("Hoboken United",                          "Hoboken",               "NJ"),
    ("Holmdel FC",                              "Holmdel",               "NJ"),
    ("Horsham Soccer",                          "Horsham",               "PA"),
    ("Howell United SC",                        "Howell",                "NJ"),
    ("Hudson Valley Premier Program",           "Newburgh",              "NY"),
    ("Hulmeville SC",                           "Hulmeville",            "PA"),
    ("Hunter SC",                               "Quakertown",            "PA"),
    ("Huntingdon Valley AA",                    "Huntingdon Valley",     "PA"),
    ("Inter NJ Soccer Club",                    "Kearny",                "NJ"),
    ("Iron Valley United SC",                   "Lebanon",               "PA"),
    ("Ironbound SC",                            "Newark",                "NJ"),
    ("Ives Estates PSG",                        "Miami",                 "FL"),
    ("Jackson SC",                              "Jackson",               "NJ"),
    ("JAE Academy Plainfield",                  "Plainfield",            "NJ"),
    ("JCFC Academy",                            "Unknown",               "CT"),
    ("Jersey City Soccer Association",          "Jersey City",           "NJ"),
    ("Jersey Crew SC",                          "Midland Park",          "NJ"),
    ("Jersey Elite Soccer Academy",             "Parsippany",            "NJ"),
    ("Jersey Knights SC",                       "Wayne",                 "NJ"),
    ("Jersey Rangers Soccer Academy",           "Clifton",               "NJ"),
    ("Jersey Shore Boca Jr FC",                 "Point Pleasant",        "NJ"),
    ("Jersey South FC",                         "Evesham",               "NJ"),
    ("Juventus Academy Miami",                  "Miami",                 "FL"),
    ("Juventus Academy NY",                     "Brooklyn",              "NY"),
    ("Kearny Thistle United FC",                "Kearny",                "NJ"),
    ("Key Biscayne SC",                         "Key Biscayne",          "FL"),
    ("Keystone Athletic",                       "Harrisburg",            "PA"),
    ("Keystone FC",                             "Lancaster",             "PA"),
    ("Kids United - NY",                        "Brooklyn",              "NY"),
    ("King of Prussia SC",                      "King of Prussia",       "PA"),
    ("Lacey SC",                                "Lacey Township",        "NJ"),
    ("Lancaster FC",                            "Lancaster",             "PA"),
    ("Lancaster Inferno",                       "Lancaster",             "PA"),
    ("Lansdowne Yonkers FC",                    "Yonkers",               "NY"),
    ("Lehigh Valley United",                    "Bethlehem",             "PA"),
    ("Lionville SC",                            "Exton",                 "PA"),
    ("Maple Shade Soccer",                      "Maple Shade",           "NJ"),
    ("Marlboro Soccer Association",             "Marlboro",              "NJ"),
    ("Marlton Soccer Club",                     "Marlton",               "NJ"),
    ("Maryland United FC",                      "Germantown",            "MD"),
    ("Match Fit Academy FC",                    "Kearny",                "NJ"),
    ("Match Fit Surf",                          "Brick",                 "NJ"),
    ("Medford SC",                              "Medford",               "NJ"),
    ("Medford Strikers SC",                     "Medford",               "NJ"),
    ("Mercer United FC",                        "Hamilton Township",     "NJ"),
    ("Monmouth United Soccer",                  "West Long Branch",      "NJ"),
    ("Montgomery Travelers Soccer Club",        "Belle Mead",            "NJ"),
    ("Montgomery United SC",                    "Montgomery",            "NJ"),
    ("Mountain Top Youth SA",                   "Mountain Top",          "PA"),
    ("NESA",                                    "Nutley",                "NJ"),
    ("New Jersey Stallions",                    "Clifton",               "NJ"),
    ("New York Titans FC",                      "Brooklyn",              "NY"),
    ("NJ Blaze",                                "Flemington",            "NJ"),
    ("NJ Nationals FC",                         "Egg Harbor Township",   "NJ"),
    ("NJ Premier FC",                           "Somerset",              "NJ"),
    ("NJ Santos FC",                            "Elizabeth",             "NJ"),
    ("Nona Soccer Academy",                     "Lake Nona",             "FL"),
    ("North Plainfield SC",                     "North Plainfield",      "NJ"),
    ("NY Hota Bavarians SC",                    "New York",              "NY"),
    ("Oakwood Sports Center",                   "Glastonbury",           "CT"),
    ("Ocean Township United SA",                "Ocean Township",        "NJ"),
    ("Ocean United",                            "Unknown",               "NJ"),
    ("Old Bridge Soccer Club",                  "Old Bridge",            "NJ"),
    ("PA Classics",                             "Manheim",               "PA"),
    ("PA Classics Harrisburg",                  "Harrisburg",            "PA"),
    ("PA Mutiny Gold",                          "Collegeville",          "PA"),
    ("Parsippany SC",                           "Parsippany",            "NJ"),
    ("PASCO Soccer Club",                       "Paterson",              "NJ"),
    ("Passaic Youth Soccer",                    "Passaic",               "NJ"),
    ("Penn Alliance Select",                    "Allentown",             "PA"),
    ("Penn Fusion Soccer Academy",              "West Chester",          "PA"),
    ("Philadelphia International FC",          "Philadelphia",          "PA"),
    ("Philadelphia SC",                         "Philadelphia",          "PA"),
    ("Phoenixville Area SC",                    "Phoenixville",          "PA"),
    ("Pittsgrove Soccer Club",                  "Pittsgrove",            "NJ"),
    ("Plantation FC Rush",                      "Plantation",            "FL"),
    ("Princeton SA",                            "Princeton",             "NJ"),
    ("PSA SDFC",                                "Randolph",              "NJ"),
    ("Quakertown SC",                           "Quakertown",            "PA"),
    ("Radnor SC",                               "Wayne",                 "PA"),
    ("Rahway Youth Soccer",                     "Rahway",                "NJ"),
    ("RCD Espanyol de Barcelona NJ",            "West New York",         "NJ"),
    ("Real Jersey FC",                          "Unknown",               "NJ"),
    ("Ridgefield Football Club",                "Ridgefield",            "NJ"),
    ("Rose Tree Soccer Club",                   "Media",                 "PA"),
    ("Saratoga-Wilton Soccer Club",             "Saratoga Springs",      "NY"),
    ("Sayreville Soccer Club",                  "South Amboy",           "NJ"),
    ("SC Vistula Garfield",                     "Garfield",              "NJ"),
    ("Schulz Academy",                          "Orlando",               "FL"),
    ("SCP Youth Soccer",                        "Kenilworth",            "NJ"),
    ("Sevilla FC Academy Florida",              "Miami",                 "FL"),
    ("SFL Club",                                "Millburn",              "NJ"),
    ("SJEB FC",                                 "Medford",               "NJ"),
    ("Soccer Vision Academy",                   "Unknown",               "OH"),
    ("South Orlando Soccer Club",               "Orlando",               "FL"),
    ("Southampton SA",                          "Southampton",           "PA"),
    ("Southern Chester County SA",              "Avondale",              "PA"),
    ("Southern Soccer Academy",                 "Marietta",              "GA"),
    ("Sporting AC New Jersey",                  "Newark",                "NJ"),
    ("Sporting Athletic Club",                  "Newark",                "NJ"),
    ("Sporting CT",                             "Middletown",            "CT"),
    ("Springfield SC",                          "Springfield",           "NJ"),
    ("Steel United NJ",                         "Bridgewater",           "NJ"),
    ("Steel United PA",                         "Philadelphia",          "PA"),
    ("Sticks N Kicks Soccer Academy",           "Fairfield",             "NJ"),
    ("Team Challenger FC North",                "Unknown",               "OH"),
    ("Team Challenger FC South",                "Unknown",               "OH"),
    ("Top Notch Soccer New Jersey",             "Trenton",               "NJ"),
    ("Valencia Soccer Academy",                 "Edison",                "NJ"),
    ("Voorhees SA",                             "Voorhees",              "NJ"),
    ("Wall Elite SC",                           "Wall Township",         "NJ"),
    ("Wall Soccer Club",                        "Wall Township",         "NJ"),
    ("Warrington SC",                           "Warrington",            "PA"),
    ("Westbury Youth Soccer Club",              "Westbury",              "NY"),
    ("Western Lehigh United SC",                "Wescosville",           "PA"),
    ("Westfield SA",                            "Westfield",             "NJ"),
    ("Weston FC",                               "Weston",                "FL"),
    ("Weston Select Soccer Club",               "Weston",                "FL"),
    ("Williams Soccer Academy",                 "Hartford",              "CT"),
    ("Woodbridge SC",                           "Woodbridge",            "NJ"),
    ("Yardley Makefield Soccer",                "Morrisville",           "PA"),
    ("Yorktown Youth Soccer Club",              "Yorktown Heights",      "NY"),
]


def main():
    os.makedirs(DATA_DIR, exist_ok=True)
    out_path = os.path.join(DATA_DIR, "edp_clubs.csv")
    fields = ["club_name", "city", "state", "league", "tier", "tier_label", "source"]

    rows = []
    for name, city, state in EDP_CLUBS:
        rows.append({
            "club_name":   name,
            "city":        city,
            "state":       state,
            "league":      "EDP Soccer",
            "tier":        "T2",
            "tier_label":  "Competitive Travel",
            "source":      "myclubscout.com/leagues/edp-soccer",
        })

    with open(out_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)

    from collections import Counter
    by_state = Counter(r["state"] for r in rows)
    print(f"Saved {len(rows)} EDP clubs -> {out_path}")
    print("Top states: " + ", ".join(f"{s}({c})" for s, c in by_state.most_common(8)))


if __name__ == "__main__":
    main()
