#!/usr/bin/env python3
"""
Pull survey responses from the master Google Sheet (Tally + imported
Typeform rows) and regenerate everything downstream of it:
  - the RESPONSES data block in survey.html
  - data/survey_merged.csv (read by report/costs.html survey chart)

The sheet is the source of truth; edit dollar amounts there, then rerun:
    python3 scripts/sheet_to_survey.py
"""

import csv
import io
import json
import re
import urllib.request
from datetime import datetime

SHEET_ID = "1iODVCCaoBir9sAI5t7zTWzNneGWVrSase8QGjhYTRMc"
SHEET_CSV = f"https://docs.google.com/spreadsheets/d/{SHEET_ID}/export?format=csv"
MERGED_CSV = "data/survey_merged.csv"  # exact legacy dollar amounts
SURVEY_HTML = "survey.html"

BEGIN = "// === SURVEY DATA (generated by scripts/sheet_to_survey.py — do not edit by hand) ==="
END = "// === END SURVEY DATA ==="

# Known duplicate submissions: same response arriving via two pipelines.
DUPLICATE_IDS = {"tally_20260610_1550"}

# League attributions previously published on the page for rows whose
# league column is blank in the sheet (legacy Typeform answers).
LEAGUE_OVERRIDES = {
    "vXBZ82d": "ECNL",                              # Sporting California
    "Dq1ljpb": "DPL",                               # Rangers FC
    "ecobyt7arroje4qvf4t1eecobyt7axeq": "ECNL",     # Slammers
    "r54j6ih1u6uy0ew3r546znka7eplr4g7": "ECNL",     # SoCal Blues
    "lb9d35lv1kd0plb9b452ahg4mb09at6v": "MLS NEXT", # Strikers FC academy
}

# "Please specify" free text -> canonical league label
SPECIFY_MAP = {
    "ea": "EA (Elite Academy)",
    "mls next": "MLS NEXT — Homegrown (HG)",
}

# League -> club_level bucket for survey_merged.csv (matches the levels the
# legacy Typeform asked for directly). Used only for rows the merged CSV
# hasn't seen before; existing rows keep their original level.
def league_level(league):
    if league.startswith("MLS NEXT"):
        return "Academy"
    if league.startswith("EA"):
        return "EA (Elite Academy)"
    if league in ("ECNL", "ECNL RL", "DPL", "GA", "Girls Academy"):
        return "Elite club"
    if league == "AYSO":
        return "Rec"
    return "Competitive travel"

# Tally private-coaching ranges: (low, high, midpoint estimate)
COACHING_RANGES = {
    "$0": (0, 0, 0),
    "$0-$500": (0, 500, 250),
    "$500-$2000": (500, 2000, 1250),
    "$2,000+": (2000, float("inf"), 2500),
}

COL = {
    "id": "Submission ID",
    "submitted": "Submitted at",
    "gender": "What gender league do they play in?",
    "age": "What age group?",
    "league": "What league does your child's team compete in?",
    "specify": "Please specify the league here. ",
    "travel_scope": "How far does your team typically travel for games?",
    "sessions": "How many sessions per week does your child spend in club practice?",
    "club_fee": "What are your annual club fees?",
    "league_fee": "If seperate from club fees. What are your annual league fees?",
    "tournament": "What are your annual tournament fees?",
    "uniform": "What are your annual uniform/kit fees?",
    "travel": "Estimated travel costs?",
    "coaching": "How much do you spend on private coaching per year?",
    "zip": "Please provide your zip code for regional analysis.",
    "income": "Which of these best describes your household income bracket?",
}


def money(val):
    """'$3,300' -> 3300; '' -> None."""
    if not val or not val.strip():
        return None
    cleaned = re.sub(r"[$,\s]", "", val)
    try:
        return int(float(cleaned))
    except ValueError:
        return None


def parse_date(val):
    for fmt in ("%m/%d/%Y %H:%M:%S", "%m/%d/%Y %H:%M", "%Y-%m-%d %H:%M:%S"):
        try:
            return datetime.strptime(val.strip(), fmt).strftime("%Y-%m-%d")
        except ValueError:
            continue
    return val.strip()[:10]


def coaching_estimate(raw, exact):
    """Resolve private coaching to a dollar estimate.

    Prefer the exact legacy amount when it agrees with the range shown in
    the sheet; otherwise fall back to the range midpoint."""
    n = money(raw)
    if n is not None:
        return n
    rng = COACHING_RANGES.get(raw.strip()) if raw else None
    if rng is None:
        return None
    low, high, mid = rng
    if exact is not None and low <= exact <= high:
        return exact
    return mid


def resolve_league(r):
    league = (r[COL["league"]] or "").strip()
    if league:
        return league
    specify = (r[COL["specify"]] or "").strip().lower()
    if specify in SPECIFY_MAP:
        return SPECIFY_MAP[specify]
    return LEAGUE_OVERRIDES.get(r[COL["id"]].strip(), "Other / Unspecified")


MERGED_FIELDS = [
    "submission_id", "submitted_at", "zip_code", "income_bracket",
    "club_level", "club_name", "travel_scope",
    "club_fee_annual", "league_fee_annual", "private_coaching_annual",
    "travel_annual", "equipment_annual", "tournament_annual",
    "training_hours_week", "private_coaching_hours_week",
    "years_in_club", "recruited", "total_annual_est",
]


def write_merged_csv(responses, prev_merged):
    """Regenerate data/survey_merged.csv from sheet rows. The sheet is the
    source of truth for dollar amounts; fields the sheet doesn't carry
    (club_level, hours, tenure) are preserved from the previous CSV.
    club_name stays blank — never published per survey promise."""
    out = []
    for r in responses:
        prev = prev_merged.get(r["id"], {})
        out.append({
            "submission_id": r["id"],
            "submitted_at": prev.get("submitted_at") or r["date"],
            "zip_code": r["zip"] or "",
            "income_bracket": r["income"] or "",
            "club_level": prev.get("club_level") or league_level(r["league"]),
            "club_name": "",
            "travel_scope": r["travel_scope"] or prev.get("travel_scope", ""),
            "club_fee_annual": r["club_fee"] if r["club_fee"] is not None else "",
            "league_fee_annual": r["league_fee"] if r["league_fee"] is not None else "",
            "private_coaching_annual": r["private_coaching"] if r["private_coaching"] is not None else "",
            "travel_annual": r["travel"] if r["travel"] is not None else "",
            "equipment_annual": r["uniform"] if r["uniform"] is not None else "",
            "tournament_annual": r["tournament"] if r["tournament"] is not None else "",
            "training_hours_week": prev.get("training_hours_week", ""),
            "private_coaching_hours_week": prev.get("private_coaching_hours_week", ""),
            "years_in_club": prev.get("years_in_club", ""),
            "recruited": prev.get("recruited", ""),
            "total_annual_est": r["total"],
        })
    with open(MERGED_CSV, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=MERGED_FIELDS)
        w.writeheader()
        w.writerows(out)
    print(f"Wrote {len(out)} responses to {MERGED_CSV}")


def main():
    with urllib.request.urlopen(SHEET_CSV) as resp:
        raw_rows = list(csv.DictReader(io.StringIO(resp.read().decode("utf-8"))))

    # Previous merged CSV: source of exact legacy coaching dollars and of
    # fields the sheet doesn't carry (club_level, hours, tenure).
    prev_merged = {}
    with open(MERGED_CSV, newline="", encoding="utf-8") as f:
        for r in csv.DictReader(f):
            prev_merged[r["submission_id"]] = r
    exact_coaching = {
        sid: int(r["private_coaching_annual"])
        for sid, r in prev_merged.items()
        if r.get("private_coaching_annual", "") != ""
    }

    # A duplicate row can carry an exact coaching figure for its twin
    dup_exact = {}
    for r in raw_rows:
        if r[COL["id"]].strip() in DUPLICATE_IDS:
            n = money(r[COL["coaching"]])
            if n is not None:
                dup_exact[(r[COL["zip"]].strip(), r[COL["income"]].strip())] = n

    responses = []
    for r in raw_rows:
        sid = r[COL["id"]].strip()
        if not sid or sid in DUPLICATE_IDS:
            continue

        exact = exact_coaching.get(sid)
        if exact is None:
            exact = dup_exact.get((r[COL["zip"]].strip(), r[COL["income"]].strip()))

        rec = {
            "id": sid,
            "date": parse_date(r[COL["submitted"]]),
            "league": resolve_league(r),
            "age": r[COL["age"]].strip() or None,
            "travel_scope": r[COL["travel_scope"]].strip() or None,
            "zip": r[COL["zip"]].strip() or None,
            "income": r[COL["income"]].strip() or None,
            "sessions": money(r[COL["sessions"]]),
            "club_fee": money(r[COL["club_fee"]]),
            "league_fee": money(r[COL["league_fee"]]),
            "tournament": money(r[COL["tournament"]]),
            "uniform": money(r[COL["uniform"]]),
            "travel": money(r[COL["travel"]]),
            "private_coaching": coaching_estimate(r[COL["coaching"]], exact),
        }
        rec["total"] = sum(
            rec[k] or 0
            for k in ("club_fee", "league_fee", "tournament",
                      "uniform", "travel", "private_coaching")
        )
        responses.append(rec)

    responses.sort(key=lambda r: r["date"])

    write_merged_csv(responses, prev_merged)

    js = "  const RESPONSES = " + json.dumps(responses, indent=2, ensure_ascii=False) + ";"
    js = "\n".join("  " + line if i else line for i, line in enumerate(js.split("\n")))

    with open(SURVEY_HTML, encoding="utf-8") as f:
        html = f.read()

    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    block = f"{BEGIN}\n{js}\n  {END}"
    if pattern.search(html):
        html = pattern.sub(lambda _: block, html)
    else:
        raise SystemExit(f"Markers not found in {SURVEY_HTML}; add them around the RESPONSES array.")

    with open(SURVEY_HTML, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"Wrote {len(responses)} responses into {SURVEY_HTML}")
    for r in responses:
        print(f"  {r['date']}  {r['league']:<28} total=${r['total']:>6,}  zip={r['zip'] or '—'}")


if __name__ == "__main__":
    main()
